version: '3.8'

services:
  app:
    build: .
    container_name: sto-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15-alpine
    container_name: sto-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-sto}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 